### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by t-imamichi**
### Summary

Fix mypy error in main branch.
https://github.com/qiskit-community/qiskit-optimization/actions/runs/6172901069

Also fixes following items
- qiskit.utils -> qiskit_algorithms.utils
- minimum scipy version that supports `ScipyMilpOptimizer`.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
I imagine this is ready since things now pass - you still have WIP in the title.

**Comment by t-imamichi** [comment]
Today's schedule CI fails due to the error.
https://github.com/qiskit-community/qiskit-optimization/actions/runs/6179936412

**Comment by t-imamichi** [comment]
I also fixed `from qiskit.utils import algorithm_globals` used in a qrao test.

**Comment by woodsp-ibm** [comment]
Can you fix one other place  too - this is a validation function that was used by algos. It will be deprecated/removed from Qiskit and was "moved" to qiskit_algorithms too. https://github.com/qiskit-community/qiskit-optimization/blob/b5b8de828afc9c38dc23262eea293f375085b447/qiskit_optimization/algorithms/recursive_minimum_eigen_optimizer.py#L20

(Simply change from qiskit.utils... to from qiskit_algorithms.utils...

**Comment by t-imamichi** [comment]
Thanks. I did it.
I also updated the minimum version of scipy to support `ScipiMilpOptimizer`.

**Comment by woodsp-ibm** [comment]
For this

> I also updated the minimum version of scipy to support ScipyMilpOptimizer.

the SciPyMilpOptimizer before, and in fact as it still is, is treated as an optional and has conditional logic around that. With bumping the version of scipy that conditional optional logic is not really needed anymore right? Maybe that was done more due to the fact that 3.7 was still supported here and Scipy was 3.8 or above for that version. So bottom line should we get rid of the optional logic there now with this being bumped - its irrelevant after this change.

**Review by woodsp-ibm — COMMENTED** [review]
LGTM

**Comment by t-imamichi** [comment]
Thanks. I approve and merge it.

**Review by woodsp-ibm — APPROVED** [review]
Sorry my bad - the LGTM comment was supposed to have been an Approve!

**Comment by t-imamichi** [comment]
Thank you for merging it.

**Pull request merged**
