### PR TITLE
Update CPLEX-incompatible Python version in documentation 

### PR DESCRIPTION
**Pull request by larsschellhas**
### Summary
Updates the version number of Python for which no CPLEX version exists, yet.
In this case, updating from 3.9 to 3.12.

This fixes issue #591.

### Details and comments

No more details required.

### CODE REVIEW

**Comment by woodsp-ibm** [comment]
Given something specific will always be out of date maybe it needs to be a more generic statement there. As it stands Qiskit Optimization also does not officially support 3.12 yet, see #590 - though I imagine its likely it works.

So perhaps instead of something specific, i.e.

`Currently there is no Python 3.12 version of CPLEX. In this case, the CPLEX install command will have no effect.`

Perhaps it ought to be changed to something more like

`CPLEX is a separate package and its support of Python versions is independent of Qiskit Optimization, where this CPLEX command will have no effect if there is not (yet) a compatible version of CPLEX available.`

**Comment by larsschellhas** [comment]
@woodsp-ibm, of course, makes sense. I've updated the respective sections.

**Review by t-imamichi — APPROVED** [review]
Thank you for your contribution. LGTM.

**Review by woodsp-ibm — APPROVED** [review]
Thanks for the contribution in improving the docs.

**Pull request merged**
